### ISSUE TITLE
Day1_ExceptionHandling

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/Standard_of_Java#1]
1. 예외 클래스의 계층 구조
2. try - catch문에서의 흐름
3. 예외 발생과 catch블럭
4. 예외 발생시키기
5. 메서드에 예외 선언하기

다음 내용들에 대한 블로그를 작성하시고 코멘트를 달아주시기 바랍니다.

**Comment by YunWonYong** [comment]
안녕하세요.  스터디 참여할 수 있나요??

**Comment by randi65535** [comment]
https://docs.google.com/document/d/12vEDXQne7nmpYZiRTLKyxaPsrQ3kh7UxJktS86d0PsM/edit?usp=sharing

**Comment by ilgolf** [comment]
https://golf-dev.tistory.com/4
