### ISSUE TITLE
Day2_ExceptionHandling

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/Standard_of_Java#2]
1. finally블록
2. 자동 자원 반환 - try - with - resources문
3. 사용자 정의 예외 만들기
4. 예외 던지기
5. 연결된 예외

**Comment by randi65535** [comment]
https://randi65535.notion.site/2-fa3a8773d2ce487793c96e5951876e4d

**Comment by ilgolf** [comment]
https://golf-dev.tistory.com/5
